# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='news_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
